services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    # tty: true、もしくはフォアグラウンドで実行しているプロセスがあればコンテナが停止しない
    tty: true
    # source(ホストマシン)のディレクトリをtarget(コンテナ)にマウントする
    volumes:
      - type: bind
        source: ./app
        target: /app
    #コンテナ内のワーキングディレクトリ
    working_dir: /app