services:
  app:
    container_name: aboutme_app
    build:
      # context: .
      dockerfile: ./app/Dockerfile
    # tty: true、もしくはフォアグラウンドで実行しているプロセスがあればコンテナが停止しない
    tty: true
    # source(ホストマシン)のディレクトリをtarget(コンテナ)にマウントする
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /app
    #コンテナ内のワーキングディレクトリ
    # working_dir: /app